import { Router } from 'express';
import * as AuthController from '../controllers/auth.controller.js';
import { requireAuth } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { registerSchema, loginSchema, vendorRegisterSchema, googleSchema } from '../validators/auth.validators.js';
const router = Router();
router.post('/register', validate(registerSchema), AuthController.register);
router.post('/login', validate(loginSchema), AuthController.login);
router.post('/vendor/register', validate(vendorRegisterSchema), AuthController.vendorRegister);
router.post('/google', validate(googleSchema), AuthController.google);
router.get('/me', requireAuth, AuthController.me);
export default router;
