import { Router } from 'express';
import * as CustomerController from '../controllers/customer.controller.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { acceptQuoteBodySchema, idParamSchema, reviewCreateSchema } from '../validators/common.validators.js';
const router = Router();
router.use(requireAuth, requireRole('customer'));
router.get('/dashboard-stats', CustomerController.getDashboardStats);
router.get('/bookings', CustomerController.getBookings);
router.post('/bookings/:id/cancel', validate(idParamSchema), CustomerController.cancelBooking);
router.post('/bookings/:id/pay-advance', validate(idParamSchema), CustomerController.payAdvance);
router.post('/bookings/:id/pay-balance', validate(idParamSchema), CustomerController.payBalance);
router.post('/bookings/:id/pay-full', validate(idParamSchema), CustomerController.payFull);
router.get('/quotes', CustomerController.getQuotes);
router.post('/quotes/:id/accept', validate(acceptQuoteBodySchema), CustomerController.acceptQuote);
router.post('/quotes/:id/decline', validate(idParamSchema), CustomerController.declineQuote);
router.get('/reviews', CustomerController.getReviews);
router.post('/reviews', validate(reviewCreateSchema), CustomerController.createReview);
router.patch('/profile', CustomerController.updateProfile);
export default router;
