/** Canonical vehicle catalog — seed source of truth for names/slugs. */
export const VEHICLE_TYPE_SEED = [
  { slug: 'mini-bus', name: 'Mini bus', category: 'bus', seatsMin: 12, seatsMax: 25, featured: true, sortOrder: 10 },
  { slug: 'tempo-traveller', name: 'Tempo Traveller', category: 'bus', seatsMin: 9, seatsMax: 17, featured: true, sortOrder: 20 },
  { slug: 'force-traveller', name: 'Force Traveller', category: 'bus', seatsMin: 9, seatsMax: 26, featured: true, sortOrder: 18 },
  { slug: 'tata-winger', name: 'Tata Winger', category: 'bus', seatsMin: 9, seatsMax: 13, featured: true, sortOrder: 19 },
  { slug: 'luxury-bus', name: 'Luxury bus', category: 'bus', seatsMin: 30, seatsMax: 45, featured: true, sortOrder: 30 },
  { slug: 'sleeper-bus', name: 'Sleeper bus', category: 'bus', seatsMin: 20, seatsMax: 40, featured: true, sortOrder: 35 },
  { slug: 'semi-sleeper-bus', name: 'Semi-sleeper bus', category: 'bus', seatsMin: 30, seatsMax: 45, featured: true, sortOrder: 36 },
  { slug: 'ac-seater-bus', name: 'AC seater bus', category: 'bus', seatsMin: 27, seatsMax: 49, featured: true, sortOrder: 37 },
  { slug: '27-seater-bus', name: '27 seater bus', category: 'bus', seatsMin: 25, seatsMax: 27, featured: true, sortOrder: 38 },
  { slug: '32-seater-bus', name: '32 seater bus', category: 'bus', seatsMin: 30, seatsMax: 32, featured: true, sortOrder: 39 },
  { slug: 'large-coach', name: 'Large coach', category: 'coach', seatsMin: 40, seatsMax: 56, featured: true, sortOrder: 40 },
  { slug: '35-seater-bus', name: '35 seater bus', category: 'bus', seatsMin: 33, seatsMax: 35, featured: false, sortOrder: 41 },
  { slug: '40-seater-bus', name: '40 seater bus', category: 'bus', seatsMin: 38, seatsMax: 41, featured: true, sortOrder: 42 },
  { slug: '45-seater-bus', name: '45 seater bus', category: 'coach', seatsMin: 43, seatsMax: 45, featured: true, sortOrder: 43 },
  { slug: '49-seater-coach', name: '49 seater coach', category: 'coach', seatsMin: 47, seatsMax: 49, featured: false, sortOrder: 44 },
  { slug: 'luxury-coach', name: 'Luxury Coach', category: 'coach', seatsMin: 40, seatsMax: 56, featured: true, sortOrder: 45 },
  { slug: '53-seater-coach', name: '53 seater coach', category: 'coach', seatsMin: 51, seatsMax: 53, featured: false, sortOrder: 46 },
  { slug: 'luxury-sleeper-coach', name: 'Luxury sleeper coach', category: 'coach', seatsMin: 20, seatsMax: 36, featured: true, sortOrder: 47 },
  { slug: 'mini-coach', name: 'Mini coach', category: 'coach', seatsMin: 18, seatsMax: 30, featured: false, sortOrder: 48 },
  { slug: 'midi-bus', name: 'Midi bus', category: 'bus', seatsMin: 22, seatsMax: 32, featured: false, sortOrder: 49 },
  { slug: 'volvo-buses', name: 'Volvo buses', category: 'coach', seatsMin: 35, seatsMax: 49, featured: true, sortOrder: 50 },
  { slug: 'volvo-9400', name: 'Volvo 9400', category: 'coach', seatsMin: 45, seatsMax: 53, featured: true, sortOrder: 51 },
  { slug: 'scania-coach', name: 'Scania coach', category: 'coach', seatsMin: 40, seatsMax: 53, featured: true, sortOrder: 52 },
  { slug: 'mercedes-coach', name: 'Mercedes coach', category: 'coach', seatsMin: 35, seatsMax: 49, featured: false, sortOrder: 60 },
  { slug: 'bharatbenz-bus', name: 'Bharatbenz bus', category: 'bus', seatsMin: 30, seatsMax: 49, featured: false, sortOrder: 70 },
  { slug: 'ashok-leyland-bus', name: 'Ashok Leyland bus', category: 'bus', seatsMin: 30, seatsMax: 49, featured: false, sortOrder: 75 },
  { slug: 'eicher-bus', name: 'Eicher bus', category: 'bus', seatsMin: 20, seatsMax: 40, featured: false, sortOrder: 76 },
  { slug: 'tata-bus', name: 'Tata bus', category: 'bus', seatsMin: 20, seatsMax: 49, featured: false, sortOrder: 77 },
  { slug: 'bus-with-washroom', name: 'Bus with washroom', category: 'bus', seatsMin: 30, seatsMax: 45, featured: false, sortOrder: 80 },
  { slug: 'electric-bus', name: 'Electric bus', category: 'bus', seatsMin: 20, seatsMax: 45, featured: true, sortOrder: 85 },
  { slug: 'toyota-minibus', name: 'Toyota minibus', category: 'bus', seatsMin: 12, seatsMax: 26, featured: false, sortOrder: 90 },
  { slug: 'isuzu-bus', name: 'Isuzu bus', category: 'bus', seatsMin: 20, seatsMax: 35, featured: false, sortOrder: 100 },
  { slug: 'mitsubishi-bus', name: 'Mitsubishi bus', category: 'bus', seatsMin: 20, seatsMax: 35, featured: false, sortOrder: 110 },
  { slug: 'motorhome', name: 'Motorhome', category: 'specialty', seatsMin: 2, seatsMax: 8, featured: false, sortOrder: 120 },
  { slug: 'double-decker-bus', name: 'Double decker bus', category: 'specialty', seatsMin: 60, seatsMax: 80, featured: false, sortOrder: 125 },
  { slug: 'urbania', name: 'Urbania', category: 'bus', seatsMin: 9, seatsMax: 17, featured: true, sortOrder: 15, description: 'Force Urbania premium van for executive and employee travel.' },
  { slug: 'force-urbania', name: 'Force Urbania', category: 'bus', seatsMin: 9, seatsMax: 17, featured: true, sortOrder: 16 },
  { slug: 'cab', name: 'Cab', category: 'cab', seatsMin: 3, seatsMax: 4, featured: true, sortOrder: 200 },
  { slug: 'sedan', name: 'Sedan', category: 'cab', seatsMin: 3, seatsMax: 4, featured: true, sortOrder: 210 },
  { slug: 'suv', name: 'SUV', category: 'cab', seatsMin: 5, seatsMax: 7, featured: true, sortOrder: 220 },
  { slug: 'muv', name: 'MUV', category: 'cab', seatsMin: 6, seatsMax: 8, featured: true, sortOrder: 230 },
  { slug: 'hatchback', name: 'Hatchback', category: 'cab', seatsMin: 3, seatsMax: 4, featured: false, sortOrder: 240 },
  { slug: 'innova-crysta', name: 'Innova Crysta', category: 'cab', seatsMin: 6, seatsMax: 7, featured: true, sortOrder: 250 },
  { slug: 'innova-hycross', name: 'Innova Hycross', category: 'cab', seatsMin: 6, seatsMax: 7, featured: true, sortOrder: 251 },
  { slug: 'kia-carnival', name: 'Kia Carnival', category: 'cab', seatsMin: 6, seatsMax: 7, featured: true, sortOrder: 252 },
  { slug: 'toyota-innova', name: 'Toyota Innova', category: 'cab', seatsMin: 6, seatsMax: 8, featured: true, sortOrder: 253 },
  { slug: 'ertiga', name: 'Ertiga', category: 'cab', seatsMin: 6, seatsMax: 7, featured: false, sortOrder: 254 },
  { slug: 'fortuner', name: 'Fortuner', category: 'cab', seatsMin: 6, seatsMax: 7, featured: false, sortOrder: 255 },
  { slug: 'dzire', name: 'Dzire', category: 'cab', seatsMin: 3, seatsMax: 4, featured: false, sortOrder: 256 },
  { slug: 'bolero', name: 'Bolero', category: 'cab', seatsMin: 6, seatsMax: 9, featured: false, sortOrder: 257 },
  { slug: 'employee-shuttle', name: 'Employee Shuttle', category: 'shuttle', seatsMin: 12, seatsMax: 40, featured: true, sortOrder: 300 },
  { slug: 'corporate-shuttle', name: 'Corporate Shuttle', category: 'shuttle', seatsMin: 12, seatsMax: 45, featured: true, sortOrder: 310 },
  { slug: 'airport-shuttle', name: 'Airport Shuttle', category: 'shuttle', seatsMin: 8, seatsMax: 40, featured: true, sortOrder: 320 },
  { slug: 'staff-bus', name: 'Staff bus', category: 'shuttle', seatsMin: 20, seatsMax: 49, featured: true, sortOrder: 305 },
  { slug: 'school-bus', name: 'School bus', category: 'shuttle', seatsMin: 20, seatsMax: 52, featured: true, sortOrder: 306 },
];

export const VEHICLE_CATEGORIES = ['bus', 'coach', 'cab', 'shuttle', 'specialty'];

export const slugify = (text = '') =>
  String(text)
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
